/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

/**
 * @file nrf_modem_at_wrapper.c
 * Wrapper for nrf_modem_at_cmd to handle custom AT commands in tests
 */

#include <string.h>
#include <strings.h>
#include <stdarg.h>
#include <errno.h>
#include <stdio.h>
#include <nrf_modem_at.h>
#include <modem/at_cmd_custom.h>

/* CMock-generated internal function for handling mock expectations.
 * Not in header because CMock doesn't generate declarations for variadic functions.
 */
extern int __cmock_nrf_modem_at_cmd(void *buf, size_t len, const char *fmt, ...);

/* Forward declarations for custom command wrapper functions */
/* These are generated by SM_AT_CMD_CUSTOM macro */
extern int handle_at_socket_wrapper_xsocket(char *buf, size_t len, char *at_cmd);
extern int handle_at_close_wrapper_xclose(char *buf, size_t len, char *at_cmd);
extern int handle_at_bind_wrapper_xbind(char *buf, size_t len, char *at_cmd);
extern int handle_at_connect_wrapper_xconnect(char *buf, size_t len, char *at_cmd);
extern int handle_at_send_wrapper_xsend(char *buf, size_t len, char *at_cmd);
extern int handle_at_recv_wrapper_xrecv(char *buf, size_t len, char *at_cmd);
extern int handle_at_sendto_wrapper_xsendto(char *buf, size_t len, char *at_cmd);
extern int handle_at_recvfrom_wrapper_xrecvfrom(char *buf, size_t len, char *at_cmd);
extern int handle_at_getaddrinfo_wrapper_xgetaddrinfo(char *buf, size_t len, char *at_cmd);
extern int handle_at_xapoll_wrapper_xapoll(char *buf, size_t len, char *at_cmd);
extern int handle_at_recvcfg_wrapper_xrecvcfg(char *buf, size_t len, char *at_cmd);
extern int handle_at_socketopt_wrapper_xsocketopt(char *buf, size_t len, char *at_cmd);
extern int handle_at_secure_socket_wrapper_xssocket(char *buf, size_t len, char *at_cmd);
extern int handle_at_secure_socketopt_wrapper_xssocketopt(char *buf, size_t len, char *at_cmd);

/* Wrapper for nrf_modem_at_cmd that handles custom commands */
int nrf_modem_at_cmd(void *buf, size_t buf_size, const char *fmt, ...)
{
	va_list args;
	char at_cmd[256];
	int ret;

	/* Format the command string */
	va_start(args, fmt);
	ret = vsnprintf(at_cmd, sizeof(at_cmd), fmt, args);
	va_end(args);

	if (ret < 0 || ret >= (int)sizeof(at_cmd)) {
		return -EINVAL;
	}

	/* Check if this is a Serial Modem custom command (starts with AT#) */
	if (strncasecmp(at_cmd, "AT#", 3) == 0) {
		/* Route to appropriate handler based on command */
		/* NOTE: Check longer commands before shorter ones to avoid prefix matches */
		if (strncasecmp(at_cmd, "AT#XSOCKETOPT", 13) == 0) {
			ret = handle_at_socketopt_wrapper_xsocketopt((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XSSOCKETOPT", 14) == 0) {
			ret = handle_at_secure_socketopt_wrapper_xssocketopt((char *)buf, buf_size,
									     at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XSOCKET", 10) == 0) {
			ret = handle_at_socket_wrapper_xsocket((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XSSOCKET", 11) == 0) {
			ret = handle_at_secure_socket_wrapper_xssocket((char *)buf, buf_size,
								       at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XCLOSE", 9) == 0) {
			ret = handle_at_close_wrapper_xclose((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XBIND", 8) == 0) {
			ret = handle_at_bind_wrapper_xbind((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XCONNECT", 11) == 0) {
			ret = handle_at_connect_wrapper_xconnect((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XSENDTO", 10) == 0) {
			ret = handle_at_sendto_wrapper_xsendto((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XSEND", 8) == 0) {
			ret = handle_at_send_wrapper_xsend((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XRECVCFG", 11) == 0) {
			ret = handle_at_recvcfg_wrapper_xrecvcfg((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XRECVFROM", 12) == 0) {
			ret = handle_at_recvfrom_wrapper_xrecvfrom((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XRECV", 8) == 0) {
			ret = handle_at_recv_wrapper_xrecv((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XGETADDRINFO", 15) == 0) {
			ret = handle_at_getaddrinfo_wrapper_xgetaddrinfo((char *)buf, buf_size,
									 at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XAPOLL", 9) == 0) {
			ret = handle_at_xapoll_wrapper_xapoll((char *)buf, buf_size, at_cmd);
		} else {
			/* Unknown custom command - return error */
			return -EINVAL;
		}

		return ret;
	}

	/* Not a custom command - delegate to CMock */
	return __cmock_nrf_modem_at_cmd(buf, buf_size, "%s", at_cmd);
}
