CONFIG_MEMFAULT_FOTA_MODEM_UPDATE=y
CONFIG_MEMFAULT_FOTA_MODEM_SOFTWARE_TYPE="host"

# Update with a new project key, see https://docs.memfault.com/docs/mcu/nrf-modem-fota
CONFIG_MEMFAULT_FOTA_MODEM_PROJECT_KEY="YOUR_PROJECT_KEY"
