#
# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable external flash for full FOTA
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y

# Full modem FOTA required settings
CONFIG_DFU_TARGET=y
CONFIG_DFU_TARGET_STREAM=y
CONFIG_DFU_TARGET_FULL_MODEM=y
CONFIG_ZCBOR=y
CONFIG_FMFU_FDEV=y
CONFIG_FMFU_FDEV_SKIP_PREVALIDATION=n
CONFIG_PSA_WANT_ALG_SHA_256=y
CONFIG_STREAM_FLASH_INSPECT=n

# Enable full FOTA support
CONFIG_SM_FULL_FOTA=y
