#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_NRF_PROVISIONING=y
CONFIG_NRF_PROVISIONING_HTTP=n
CONFIG_NRF_PROVISIONING_COAP=y
CONFIG_NRF_PROVISIONING_WITH_CERT=y
CONFIG_NRF_PROVISIONING_ROOT_CA_SEC_TAG=42384
CONFIG_NRF_PROVISIONING_PROVIDE_ATTESTATION_TOKEN=y
CONFIG_NRF_PROVISIONING_LOG_LEVEL_INF=y

# Timeout for waiting for the modem to enter the desired connectivity state during provisioning.
CONFIG_NRF_PROVISIONING_MODEM_STATE_WAIT_TIMEOUT_SECONDS=120

# Scheduled provisioning is not needed for Serial Modem, as the provisioning is triggered by the host.
CONFIG_NRF_PROVISIONING_SCHEDULED=n
CONFIG_NRF_PROVISIONING_AUTO_START_ON_INIT=n

# Provisioning message content format
CONFIG_NRF_PROVISIONING_CODEC=y
CONFIG_NRF_PROVISIONING_CBOR=y
CONFIG_ZCBOR=y
CONFIG_ZCBOR_CANONICAL=y

# Max provisioning commands per response
CONFIG_NRF_PROVISIONING_CBOR_RECORDS=10

# Adjust provisioning and buffer sizes to handle nRF Cloud certs
CONFIG_NRF_PROVISIONING_RX_BUF_SZ=2304
CONFIG_NRF_PROVISIONING_TX_BUF_SZ=2304
CONFIG_NRF_PROVISIONING_CODEC_AT_CMD_LEN=2048

# CoAP client
CONFIG_COAP=y
CONFIG_COAP_EXTENDED_OPTIONS_LEN=y
CONFIG_COAP_CLIENT=y

# Modem key management
CONFIG_MODEM_KEY_MGMT=y
CONFIG_MODEM_ATTEST_TOKEN=y
