#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable UART logging backend - shared with nRF modem traces.
CONFIG_UART_CONSOLE=y
CONFIG_RTT_CONSOLE=n
CONFIG_LOG_BACKEND_RTT=n
# Log backend starts disabled; the UART is off until activated via AT#XLOG=1.
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_UART_AUTOSTART=n

# Enable UART modem trace backend - shared with the UART log backend.
CONFIG_SM_MODEM_TRACE_BACKEND_UART=y
CONFIG_NRF_MODEM_LIB_TRACE=y
# Modem trace level is controlled at runtime via AT#XTRACE. Start with traces off.
CONFIG_NRF_MODEM_LIB_TRACE_LEVEL_OVERRIDE=y
CONFIG_NRF_MODEM_LIB_TRACE_LEVEL_OFF=y
