#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# CMUX trace backend for modem coredump
CONFIG_NRF_MODEM_LIB_TRACE=y
CONFIG_NRF_MODEM_LIB_TRACE_BACKEND_CMUX=y
# Configure the modem trace level to coredump only
CONFIG_NRF_MODEM_LIB_TRACE_LEVEL_OVERRIDE=y
CONFIG_NRF_MODEM_LIB_TRACE_LEVEL_COREDUMP_ONLY=y
