#
# Copyright (c) 2023 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Disable the partition manager. Use DTS to define the flash and ram partitions.
SB_CONFIG_PARTITION_MANAGER=n

# Enable immutable bootloader.
SB_CONFIG_SECURE_BOOT_APPCORE=y
SB_CONFIG_SECURE_BOOT_NUM_VER_COUNTER_SLOTS=40

# Enable updatable MCUboot bootloader.
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Provide the keys to enable updating MCUboot and application.
#SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="/home/user/ncs/_keys/mcuboot_priv.pem"
#SB_CONFIG_SECURE_BOOT_SIGNING_KEY_FILE="/home/user/ncs/_keys/nsib_priv.pem"

# Merge the hex files as a single file for easier flashing with external tools.
#SB_CONFIG_MERGED_HEX_FILES=y
