#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable UART modem trace backend - shared with the UART log backend.
CONFIG_SM_MODEM_TRACE_BACKEND_UART=y
CONFIG_NRF_MODEM_LIB_TRACE=y
# Modem trace level is controlled at runtime via AT#XTRACE. Start with traces off.
CONFIG_NRF_MODEM_LIB_TRACE_LEVEL_OVERRIDE=y
CONFIG_NRF_MODEM_LIB_TRACE_LEVEL_OFF=y
