/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

/**
 * @file nrf_modem_at_wrapper.c
 *
 * Routes AT commands to the custom handlers registered by sm_at_nrfcloud.c
 * (and the other source files included in this test build).
 *
 * The AT modem command nrf_modem_at_cmd() is used internally by sm_util.c
 * (sm_util_at_printf / sm_util_at_scanf).  This wrapper intercepts those
 * calls and:
 *   - Routes #XNRFCLOUD / #XNRFCLOUDPOS to the SM handler wrappers.
 *   - Responds to AT%NCELLMEAS=1|3|4 with a preconfigured response string
 *     so that the work-queue-driven ncellmeas flow can be driven from tests.
 *   - Responds to AT+CSCON? (RRC state query) with RRC-idle.
 *   - Returns -NRF_EINVAL for unknown commands.
 */

#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <stdarg.h>
#include <zephyr/kernel.h>
#include <nrf_modem_at.h>
#include <nrf_errno.h>
#include <modem/at_cmd_custom.h>

/* Handler wrappers generated by AT_CMD_CUSTOM in sm_at_nrfcloud.c */
extern int handle_at_nrf_cloud_wrapper_xnrfcloud(char *buf, size_t len, char *at_cmd);
extern int handle_at_nrf_cloud_pos_wrapper_xnrfcloudpos(char *buf, size_t len, char *at_cmd);

char test_at_nrfcloud_ncellmeas_resp[256];
int test_at_nrfcloud_ncellmeas_resp_ret;

int nrf_modem_at_cmd(void *buf, size_t buf_size, const char *fmt, ...)
{
	char at_cmd[256];
	va_list args;
	int ret;

	va_start(args, fmt);
	vsnprintf(at_cmd, sizeof(at_cmd), fmt, args);
	va_end(args);

	if (strncasecmp(at_cmd, "AT#XNRFCLOUDPOS", 15) == 0) {
		ret = handle_at_nrf_cloud_pos_wrapper_xnrfcloudpos(
			(char *)buf, buf_size, at_cmd);
	} else if (strncasecmp(at_cmd, "AT#XNRFCLOUD", 12) == 0) {
		ret = handle_at_nrf_cloud_wrapper_xnrfcloud(
			(char *)buf, buf_size, at_cmd);
	} else if (strncasecmp(at_cmd, "AT%NCELLMEAS", 12) == 0) {
		/* Simulate sending the AT%NCELLMEAS command to the modem.
		 * Return "OK" to sm_util_at_printf.
		 */
		if (buf && buf_size > 0) {
			strncpy((char *)buf, test_at_nrfcloud_ncellmeas_resp, buf_size - 1);
		}
		ret = test_at_nrfcloud_ncellmeas_resp_ret;
	} else if (strncasecmp(at_cmd, "AT+CSCON?", 9) == 0) {
		/* RRC connection state: 0 = idle */
		if (buf && buf_size > 0) {
			snprintf((char *)buf, buf_size, "+CSCON: 0,0\r\nOK\r\n");
		}
		ret = 0;
	} else {
		ret = -NRF_EINVAL;
	}

	return ret;
}
