/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

/**
 * @file nrf_cloud_stubs.c
 *
 * Manual stubs for nRF Cloud functions that are NOT mocked via CMock:
 *
 *  - nrf_cloud_client_id_get()   (declared in net/nrf_cloud.h)
 *  - date_time_update_async()    (declared in date_time.h)
 *
 * All nrf_cloud_coap_* functions are generated by CMock from the
 * include/net/nrf_cloud_coap.h stub header (see CMakeLists.txt).
 */

#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include "net/nrf_cloud.h"
#include "date_time.h"

/* Device-ID returned by nrf_cloud_client_id_get(). */
static const char *device_id_stub = "test-device-id";

int nrf_cloud_client_id_get(char *id_buf, size_t id_buf_sz)
{
	if (id_buf && id_buf_sz > 0) {
		strncpy(id_buf, device_id_stub, id_buf_sz - 1);
		id_buf[id_buf_sz - 1] = '\0';
	}
	return 0;
}

int date_time_update_async(date_time_evt_handler_t evt_handler)
{
	/*
	 * Immediately invoke the handler with DATE_TIME_OBTAINED_NTP so that
	 * nrfcloud_conn_work_fn's k_sem_take(&sem_date_time, K_SECONDS(10))
	 * returns at once instead of timing out.
	 */
	if (evt_handler != NULL) {
		struct date_time_evt evt = {.type = DATE_TIME_OBTAINED_NTP};

		evt_handler(&evt);
	}
	return 0;
}
