/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

/**
 * @file nrf_modem_at_wrapper.c
 *
 * Routes AT commands to the custom handlers registered by sm_at_nrfcloud.c and
 * sm_at_nrfcloud_obs.c (and the other source files included in this test build).
 *
 * The AT modem command nrf_modem_at_cmd() is used internally by sm_util.c
 * (sm_util_at_printf / sm_util_at_scanf).  This wrapper intercepts those
 * calls and:
 *   - Routes #XNRFCLOUD, #XNRFCLOUDPOS and #XNRFCLOUDOBS* to the SM handler
 *     wrappers, longest prefix first, because #XNRFCLOUD is a prefix of them all.
 *   - Responds to AT%NCELLMEAS=1|3|4 with a preconfigured response string
 *     so that the work-queue-driven ncellmeas flow can be driven from tests.
 *   - Responds to AT+CSCON? (RRC state query) with RRC-idle.
 *   - Returns -NRF_EINVAL for unknown commands.
 */

#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <stdarg.h>
#include <zephyr/kernel.h>
#include <nrf_modem_at.h>
#include <nrf_errno.h>
#include <modem/at_cmd_custom.h>

/* Handler wrappers generated by AT_CMD_CUSTOM in sm_at_nrfcloud.c */
extern int handle_at_nrf_cloud_wrapper_xnrfcloud(char *buf, size_t len, char *at_cmd);
extern int handle_at_nrf_cloud_pos_wrapper_xnrfcloudpos(char *buf, size_t len, char *at_cmd);

/* Handler wrappers generated by AT_CMD_CUSTOM in sm_at_nrfcloud_obs.c */
extern int handle_at_nrf_cloud_obs_auto_wrapper_xnrfcloudobsauto(char *buf, size_t len,
								 char *at_cmd);
extern int handle_at_nrf_cloud_obs_upload_wrapper_xnrfcloudobsupload(char *buf, size_t len,
								     char *at_cmd);
extern int handle_at_nrf_cloud_obs_heartbeat_wrapper_xnrfcloudobsheartbeat(char *buf, size_t len,
									   char *at_cmd);
extern int handle_at_nrf_cloud_obs_forward_wrapper_xnrfcloudobsforward(char *buf, size_t len,
								      char *at_cmd);
extern int handle_at_nrf_cloud_obs_devinfo_wrapper_xnrfcloudobsdevinfo(char *buf, size_t len,
								       char *at_cmd);
extern int handle_at_nrf_cloud_obs_crash_wrapper_xnrfcloudobscrash(char *buf, size_t len,
								   char *at_cmd);
extern int handle_at_nrf_cloud_obs_export_wrapper_xnrfcloudobsexport(char *buf, size_t len,
								    char *at_cmd);

/* The AT commands the modem library would dispatch on its own, ordered so that a command
 * that is a prefix of another one comes last.
 */
static const struct {
	const char *prefix;
	int (*handler)(char *buf, size_t len, char *at_cmd);
} sm_at_cmd_routes[] = {
	{"AT#XNRFCLOUDOBSAUTO", handle_at_nrf_cloud_obs_auto_wrapper_xnrfcloudobsauto},
	{"AT#XNRFCLOUDOBSUPLOAD", handle_at_nrf_cloud_obs_upload_wrapper_xnrfcloudobsupload},
	{"AT#XNRFCLOUDOBSHEARTBEAT",
	 handle_at_nrf_cloud_obs_heartbeat_wrapper_xnrfcloudobsheartbeat},
	{"AT#XNRFCLOUDOBSFORWARD", handle_at_nrf_cloud_obs_forward_wrapper_xnrfcloudobsforward},
	{"AT#XNRFCLOUDOBSDEVINFO", handle_at_nrf_cloud_obs_devinfo_wrapper_xnrfcloudobsdevinfo},
	{"AT#XNRFCLOUDOBSCRASH", handle_at_nrf_cloud_obs_crash_wrapper_xnrfcloudobscrash},
	{"AT#XNRFCLOUDOBSEXPORT", handle_at_nrf_cloud_obs_export_wrapper_xnrfcloudobsexport},
	{"AT#XNRFCLOUDPOS", handle_at_nrf_cloud_pos_wrapper_xnrfcloudpos},
	{"AT#XNRFCLOUD", handle_at_nrf_cloud_wrapper_xnrfcloud},
};

char test_at_nrfcloud_ncellmeas_resp[256];
int test_at_nrfcloud_ncellmeas_resp_ret;

int nrf_modem_at_cmd(void *buf, size_t buf_size, const char *fmt, ...)
{
	char at_cmd[256];
	va_list args;

	va_start(args, fmt);
	vsnprintf(at_cmd, sizeof(at_cmd), fmt, args);
	va_end(args);

	for (size_t i = 0; i < ARRAY_SIZE(sm_at_cmd_routes); i++) {
		const char *prefix = sm_at_cmd_routes[i].prefix;

		if (strncasecmp(at_cmd, prefix, strlen(prefix)) == 0) {
			return sm_at_cmd_routes[i].handler((char *)buf, buf_size, at_cmd);
		}
	}

	if (strncasecmp(at_cmd, "AT%NCELLMEAS", 12) == 0) {
		/* Simulate sending the AT%NCELLMEAS command to the modem.
		 * Return "OK" to sm_util_at_printf.
		 */
		if (buf && buf_size > 0) {
			strncpy((char *)buf, test_at_nrfcloud_ncellmeas_resp, buf_size - 1);
		}
		return test_at_nrfcloud_ncellmeas_resp_ret;
	}

	if (strncasecmp(at_cmd, "AT+CSCON?", 9) == 0) {
		/* RRC connection state: 0 = idle */
		if (buf && buf_size > 0) {
			snprintf((char *)buf, buf_size, "+CSCON: 0,0\r\nOK\r\n");
		}
		return 0;
	}

	return -NRF_EINVAL;
}
