#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Run Native sim in real-time mode.
CONFIG_NATIVE_SIM_SLOWDOWN_TO_REAL_TIME=y

# As of today, native_sim does not properly support UART async API with PM_RUNTIME.
#CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n

CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=20480

# Need a bit bigger than embedded targets because native_sim does not have HWFC
CONFIG_MODEM_CELLULAR_UART_BUFFER_SIZES=4256

# Use LittleFS for file system support.
CONFIG_FLASH=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FLASH_MAP=y
