#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Run Native sim in real-time mode.
CONFIG_NATIVE_SIM_SLOWDOWN_TO_REAL_TIME=y

# As of today, native_sim does not properly support UART async API with PM_RUNTIME.
#CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n

CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=20480

CONFIG_MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA=4256
CONFIG_MODEM_CELLULAR_UART_BUFFER_SIZES=4256
CONFIG_MODEM_CMUX_MSC_FC_THRESHOLD=127

# Enable AT shell (requires the modem alias defined in native_sim.overlay).
CONFIG_SHELL_WILDCARD=n
CONFIG_MODEM_AT_SHELL=y
CONFIG_MODEM_AT_USER_PIPE_IDX=0

# UART_INTERRUPT_DRIVEN on native TTY selects SERIAL_HAS_POST_KERNEL_INIT,
# which conflicts with EARLY_CONSOLE selected by NCS_BOOT_BANNER.
CONFIG_NCS_BOOT_BANNER=n
