/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

/**
 * @file nrf_modem_at_wrapper.c
 * Wrapper for nrf_modem_at_cmd that routes Serial Modem custom AT#XMQTT*
 * commands to their generated handler wrappers in tests.
 */

#include <string.h>
#include <strings.h>
#include <stdarg.h>
#include <errno.h>
#include <stdio.h>
#include <nrf_modem_at.h>
#include <modem/at_cmd_custom.h>

/* CMock-generated internal function for handling mock expectations.
 * Not in header because CMock doesn't generate declarations for variadic functions.
 */
extern int __cmock_nrf_modem_at_cmd(void *buf, size_t len, const char *fmt, ...);

/* Custom command wrapper functions generated by the SM_AT_CMD_CUSTOM macro. */
extern int handle_at_mqtt_config_wrapper_xmqttcfg(char *buf, size_t len, char *at_cmd);
extern int handle_at_mqtt_connect_wrapper_xmqttcon(char *buf, size_t len, char *at_cmd);
extern int handle_at_mqtt_publish_wrapper_xmqttpub(char *buf, size_t len, char *at_cmd);
extern int handle_at_mqtt_subscribe_wrapper_xmqttsub(char *buf, size_t len, char *at_cmd);
extern int handle_at_mqtt_unsubscribe_wrapper_xmqttunsub(char *buf, size_t len, char *at_cmd);

/* Wrapper for nrf_modem_at_cmd that handles custom commands */
int nrf_modem_at_cmd(void *buf, size_t buf_size, const char *fmt, ...)
{
	va_list args;
	char at_cmd[256];
	int ret;

	va_start(args, fmt);
	ret = vsnprintf(at_cmd, sizeof(at_cmd), fmt, args);
	va_end(args);

	if (ret < 0 || ret >= (int)sizeof(at_cmd)) {
		return -EINVAL;
	}

	/* Route Serial Modem custom commands (AT#...). Check the longer
	 * command prefixes before the shorter ones to avoid false matches.
	 */
	if (strncasecmp(at_cmd, "AT#", 3) == 0) {
		if (strncasecmp(at_cmd, "AT#XMQTTUNSUB", 13) == 0) {
			ret = handle_at_mqtt_unsubscribe_wrapper_xmqttunsub((char *)buf, buf_size,
									    at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XMQTTCFG", 11) == 0) {
			ret = handle_at_mqtt_config_wrapper_xmqttcfg((char *)buf, buf_size, at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XMQTTCON", 11) == 0) {
			ret = handle_at_mqtt_connect_wrapper_xmqttcon((char *)buf, buf_size,
								      at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XMQTTPUB", 11) == 0) {
			ret = handle_at_mqtt_publish_wrapper_xmqttpub((char *)buf, buf_size,
								      at_cmd);
		} else if (strncasecmp(at_cmd, "AT#XMQTTSUB", 11) == 0) {
			ret = handle_at_mqtt_subscribe_wrapper_xmqttsub((char *)buf, buf_size,
									at_cmd);
		} else {
			/* Unknown custom command - return error */
			return -EINVAL;
		}

		return ret;
	}

	/* Not a custom command - delegate to CMock */
	return __cmock_nrf_modem_at_cmd(buf, buf_size, "%s", at_cmd);
}
